config/routes.rb
Rails.application.routes.draw do
  resources :projects
  patch 'drag/project'
  get 'members/dashboard'
  resources :categories
  authenticated :user, ->(user) { user.admin? } do
    get 'admin', to: 'admin#index'
    get 'admin/posts'
    get 'admin/comments'
    get 'admin/users'
    get 'admin/post/:id', to: 'admin#show_post', as: 'admin_post'
  end

  get 'checkout', to: 'checkouts#show'
  get 'checkout/success', to: 'checkouts#success'
  get 'billing', to: 'billing#show'

  get 'search', to: 'search#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  get '/u/:id', to: 'users#profile', as: 'user'
  resources :after_signup

  # /posts/1/comments/4
  resources :posts do
    resources :comments
  end

  get 'about', to: 'pages#about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#home'
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  validates :title, presence: true, length: { minimum: 5, maximum: 50 }
  validates :body, presence: true
  belongs_to :category
  has_rich_text :body
  belongs_to :category

  # Single image upload
  # has_one_attached :image
  # Multiple images upload
  has_many_attached :images

  belongs_to :user
  has_many :comments, dependent: :destroy

  has_rich_text :body
  has_one :content, class_name: 'ActionText::RichText', as: :record, dependent: :destroy

  has_noticed_notifications model_name: 'Notification'
  has_many :notifications, through: :user

  friendly_id :title, use: %i[slugged history finders]

  def should_generate_new_friendly_id?
    title_changed? || slug.blank?
  end

  def views_by_day
    daily_events = Ahoy::Event.where("cast(properties ->> 'post_id' as bigint) = ?", id)
    daily_events.group_by_day(:time, range: 1.month.ago..Time.now).count
  end

  def self.total_views_by_day
    daily_events = Ahoy::Event.where(name: 'Viewed Post')
    daily_events.group_by_day(:time, range: 1.month.ago..Time.now).count
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[show index]
  # GET /posts or /posts.json
  def index
    @posts = Post.all.includes(:user, :rich_text_body).order(created_at: :desc)
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post.update(views: @post.views + 1)
    @comments = @post.comments.includes(:user, :rich_text_body).order(created_at: :desc)

    ahoy.track 'Viewed Post', post_id: @post.id

    mark_notifications_as_read
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])

    # If an old id or a numeric id was used to find the record, then
    # the request slug will not match the current slug, and we should do
    # a 301 redirect to the new path
    redirect_to @post, status: :moved_permanently if params[:id] != @post.slug
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :body, :category_id, images: [])
  end

  def mark_notifications_as_read
    if current_user
      notifications_to_mark_as_read = @post.notifications_as_post.where(recipient: current_user)
      notifications_to_mark_as_read.update_all(read_at: Time.zone.now)
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, data: {controller: "emoji-picker"}) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.select :category_id, options_for_select(Category.all.order(name: :desc).collect { |cat| [cat.name, cat.id]})%>
  </div>
  <%= content_tag(:div, "", class:"pickerContainer", data: {
    emoji_picker_target: "pickerContainer"
  }) %>
  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.rich_text_area :body, data: {
      emoji_picker_target: "trixEditor"
    } %>
  </div>
  <%= render "posts/image_form", form: form %>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_image_form.html.erb
<div class="dropzone dropzone-default dz-clickable" data-controller="dropzone" data-dropzone-max-file-size="5" data-dropzone-accepted-files="image/*" data-dropzone-max-files="2" data-upload-multiple="true">
  <%= form.file_field :images, multiple: true, direct_upload: true, data: { dropzone_target: 'input' } %>
  <div class="dropzone-msg dz-message needsclick">
    <h3 class="dropzone-msg-title">Drag here to upload or click here to browse</h3>
    <span class="dropzone-msg-desc">2 MB file size maximum. Allowed file types png, jpg.</span>
  </div>
</div>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <h2><%= post.title %></h2>
  <h4>posted by <%= link_to post.user.full_name, user_path(post.user) %></h4>
  <h6><%= pluralize(post.views, "view") %></h6>
  <% post.images.each do |image| %>
    <%= image_tag(image, style:"width:300px; height: auto")%>
  <% end %>
  <div>
    <%= post.body %>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="container">
  <h1>Editing post</h1>
  <%= render "form", post: @post %>
  <br>
  <div>
    <%= link_to "Show this post", @post %> |
    <%= link_to "Back to posts", posts_path %>
  </div>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="container">
  <h1>Posts</h1>
  <div id="posts">
    <% @posts.each do |post| %>
      <%= render post %>
      <p>
        <%= link_to "Show this post", post %>
      </p>
    <% end %>
  </div>
  <%= link_to "New post", new_post_path %>
</div>

app/views/posts/new.html.erb
<div class="container">
  <h1>New post</h1>
  <%= render "form", post: @post %>
  <br>
  <div>
    <%= link_to "Back to posts", posts_path %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <%= render @post %>
  <div>
    <%= link_to "Edit this post", edit_post_path(@post) %> |
    <%= link_to "Back to posts", posts_path %>
    <%= button_to "Destroy this post", @post, method: :delete %>
  </div>
</div>
<div class="container">
  <%= render 'comments/form', 
    post: @post, 
    comment: @post.comments.build,
    submit_label: "Reply" %>
  <% @comments.each do |comment| %>
    <%= render 'comments/comment', 
    post: @post, 
    comment: comment %>
  <% end %>
</div>